#! /bin/sh

bspc config top_padding			18

bspc config border_width        	1
bspc config window_gap          	6

bspc config split_ratio         	0.52
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance		true
#bspc config focus_follows_pointer	true

#bspc monitor -d I II III IV V VI VII VIII IX X
i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{a,b,c}
    let i++
done

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a vlc floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

nitrogen --restore &
wmname LG3D &
compton &
nm-applet &
panel &
setxkbmap pl &
